# Generated by Django 3.2.17 on 2023-02-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_uid'),
        ('account', '0004_auto_20230206_2348'),
    ]

    operations = [
    ]
