# Generated by Django 4.1.5 on 2023-02-07 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_username'),
        ('ride', '0006_alter_ride_driver_id_alter_ride_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to='account.account'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='account.account'),
        ),
    ]
