# Generated by Django 3.2.17 on 2023-02-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_rename_driver_id_ride_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car_type',
            field=models.CharField(choices=[('CM', 'compact'), ('SU', 'suv'), ('LX', 'luxury'), ('MV', 'minivan')], default='CM', max_length=2),
        ),
    ]
