# Generated by Django 4.1.5 on 2023-02-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vehicle_type',
            field=models.CharField(choices=[('CM', 'compact'), ('SU', 'suv'), ('LX', 'luxury'), ('MV', 'minivan')], default='CM', max_length=2),
        ),
    ]
