# Generated by Django 4.1.5 on 2023-02-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_alter_ride_driver_id_alter_ride_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
