# Generated by Django 3.2.17 on 2023-02-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0010_ride_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='car_type',
            new_name='vehicle_type',
        ),
    ]
