# Generated by Django 3.2.17 on 2023-02-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0011_rename_car_type_ride_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('CM', 'compact'), ('SU', 'suv'), ('LX', 'luxury'), ('MV', 'minivan')], max_length=2, null=True),
        ),
    ]
