# Generated by Django 4.1.5 on 2023-02-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_is_driver_alter_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='auser', max_length=100),
            preserve_default=False,
        ),
    ]
