# Generated by Django 4.1.5 on 2023-02-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
